### ISSUE TITLE
Sudoku 

### ISSUE THREAD

**Issue by codewithganeshhh** [codewithganeshhh/NSU-Open-source#7]
Tech Stack : HTML , CSS , JAVASCRIPT(Optional)

**Comment by RohitRaj766** [comment]
@codewithganeshhh please assign this to me.

**Comment by codewithganeshhh** [comment]
@RohitRaj766 Assigned

**Comment by codewithganeshhh** [comment]
@RohitRaj766 how much going on ?

**Comment by RohitRaj766** [comment]
> @RohitRaj766 how much going on ?

please review and merge. @codewithganeshhh

**Comment by RohitRaj766** [comment]
@codewithganeshhh please review & merge.

**Comment by codewithganeshhh** [comment]
add your project in main index.html

**Comment by RohitRaj766** [comment]
@codewithganeshhh done

**Comment by codewithganeshhh** [comment]
Thank you

**Comment by codewithganeshhh** [comment]
Thank you Mr @RohitRaj766  for contribute in our repo
